<?php

return array(
    // 'Telegram' => '',
     'Telegram bot username' => 'Nome de usuário do bot',
     'Telegram bot API key' => 'Chave de acesso do bot',
     'Chat id of private chat with bot' => 'Id da conversa privada com o bot',
     'Chat id of group chat with bot' => 'Id da conversa em grupo com o bot',
     'Help on how to generate a bot' => 'Ajuda sobre como gerar um bot',
     'Sent attachments along with notification' => 'Anexos enviados junto com a notificação',
     'Telegram bot is not configured in Kanboard settings.' => 'O bot do Telegram não está configurado nas configurações do Kanboard.',
     'Go to ' => 'Ir para ',
     'Settings > Integrations > Telegram' => 'Configurações > Integrações > Telegram',
     ' and fill the form:' => ' e preencha o formulário:',
     'Telegram bot username: Username of your Telegram Bot' => 'Nome de usuário do bot do Telegram: nome de usuário do seu bot do Telegram',
     'Telegram bot API key: HTTP API token generated by BotFather after bot creation' => 'Chave da API do bot do Telegram: token da API HTTP gerado pelo BotFather após a criação do bot',
     'Save Chat ID' => 'Salvar Id da conversa',
     'Message %s not found!' => 'Mesagem %s não encontrada!',
     'Please send message %s ' => 'Por favor, envie uma mensagem %s',
     'Save chat id="%s" from "%s"?' => 'Salvar conversa id="%s" de "$s"?',
     'To get your Telegram chat id,' => 'Para obter o seu id de conversa do Telegram,',
     '1. Send the message %s to' => '1. Envie uma mensagem %s para',
     '2. Press' => '2. Pressione',
     'Get chat id' => 'Obter Id da conversa',
);

