<?php

return array(
    'Telegram' => 'Telegram',
    'Telegram bot username' => 'Имя бота telegram',
    'Telegram bot API key' => 'Ключ API бота telegram',
    'Chat id of private chat with bot' => 'Идентификатор секретного чата с ботом',
    'Chat id of group chat with bot' => 'Идентификатор группового чата с ботом',
    'Help on how to generate a bot' => 'Помощь в создании бота',
    'Sent attachments along with notification' => 'Отправлять вложения в уведомлениях',
    'Telegram bot is not configured in Kanboard settings.' => 'Telegram бот не настроен в настройках Kanboard.',
    'Go to ' => 'Перейти к ',
    'Settings > Integrations > Telegram' => 'Настройки > Интеграции > Telegram',
    ' and fill the form:' => ' и заполните форму:',
    'Telegram bot username: Username of your Telegram Bot' => 'Имя Telegram бота: Имя пользователя вашего Telegram бота',
    'Telegram bot API key: HTTP API token generated by BotFather after bot creation' => 'API ключ Telegram бота: HTTP API токен, сгенерированный BotFather после создания бота',
    'Save Chat ID' => 'Сохранить ID чата',
    'Message %s not found!' => 'Сообщение %s не найдено!',
    'Please send message %s ' => 'Пожалуйста, отправьте сообщение  %s ',
    'Save chat id="%s" from "%s"?' => 'Сохранить чат с id="%s" из "%s"?',
    'To get your Telegram chat id,' => 'Чтобы получать id чата Telegram,',
    '1. Send the message %s to' => '1. Отправьте сообщение %s в',
    '2. Press' => '2. Нажмите',
    'Get chat id' => 'Получить id чата',
);

